name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Install the package
        run: |
          npm ci
          npm test
      -
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-radar:$(date +%s)
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jgilbotella/my-radar:latest