name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the package
        run: |
          npm ci
          npm test
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-radar:$(date +%s)