name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install the package
        run: |
          npm ci
          npm test
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-radar:$(date +%s)
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: jgibotella/my-radar
          tag_with_ref: true